from . import api
from api.scraping.MainRoute import(IndexResource)
from api.scraping.MainRoute import(FindAllOffer)
from api.scraping.MainRoute import(FindOffersByContrat)
from api.scraping.MainRoute import(FindOffersByRegion)
from api.scraping.MainRoute import(FindAllCities)
from api.scraping.MainRoute import(FindAllContrat)
from api.scraping.MainRoute import(FindOffersByContratRegion)
from api.scraping.MainRoute import(InscriptionUser)
from api.scraping.MainRoute import(LoginUser)
from api.scraping.MainRoute import(createMember)
from api.scraping.MainRoute import(listUsers)
from api.scraping.MainRoute import(LoginMember)
from api.scraping.MainRoute import(listMembers)
from api.scraping.MainRoute import(resetPassword)
from api.scraping.MainRoute import(updateStatus)
from api.scraping.MainRoute import(resetUserPassword)
from api.scraping.MainRoute import(changeUserPassword)
from api.scraping.MainRoute import(sendUserMail)
from api.scraping.MainRoute import(FindAllTypeChurch)
from api.scraping.MainRoute import(FindAllChurch)
from api.scraping.MainRoute import(FindAllCountries)
from api.scraping.MainRoute import(FindAllUsers)
from api.scraping.MainRoute import(UserDetails)
api.add_resource(IndexResource, '/')
api.add_resource(FindAllOffer, '/findOffers', '/findOffers/<filters>')
api.add_resource(FindOffersByContrat,'/FindOffersByContrat/<filters>')
api.add_resource(FindOffersByRegion,'/FindOffersByRegion/<filters>')
api.add_resource(FindOffersByContratRegion,'/FindOffersByFilter/<filters>')
api.add_resource(FindAllCities, '/findVilles')
api.add_resource(FindAllContrat, '/findContrat')
api.add_resource(InscriptionUser, '/CreateUser')
api.add_resource(FindAllUsers, '/FindUsers','/FindUsers/<filters>')
api.add_resource(UserDetails, '/UserDetails','/UserDetails/<filters>')
api.add_resource(LoginUser, '/Login')
api.add_resource(LoginMember, '/LoginMember')
api.add_resource(createMember, '/CreateMember')
api.add_resource(listUsers, '/ListUsers')
api.add_resource(FindAllChurch, '/ListChurch')
api.add_resource(FindAllTypeChurch, '/ListTypeChurch')
api.add_resource(FindAllCountries, '/ListCountry')
api.add_resource(listMembers, '/ListMembers')
api.add_resource(resetPassword,'/ResetPassword' ,'/ResetPassword/<filters>')
api.add_resource(updateStatus,'/ChangeStatus' ,'/ChangeStatus/<filters>')
api.add_resource(resetUserPassword,'/ResetUserPassword' ,'/ResetUserPassword/<filters>')
api.add_resource(changeUserPassword,'/ChangeUserPassword' ,'/ChangeUserPassword/<filters>')
api.add_resource(sendUserMail,'/SendMail' ,'/SendMail')